PizzaREAL/Models/Dish.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PizzaREAL.Models
{
    public partial class Dish
    {
        public Dish()
        {
            OrderDishes = new HashSet<OrderDish>();
            Ingredients = new HashSet<Ingredient>();
        }
        [NotMapped]
        public int DishId { get; set; }

        [DisplayName("Namn")]
        [StringLength(20, ErrorMessage = "Användarnamn kan inte vara mer än 50 tecken")]
        [Required(ErrorMessage = "Namn är obligatoriskt")]
        public string DishName { get; set; } = null!;

        [DisplayName("Beskrivning")]
        [StringLength(200, ErrorMessage = "Beskrivning kan inte vara mer än 200 tecken")]
        [Required(ErrorMessage = "Beskrivning är obligatoriskt")]
        public string Description { get; set; }

        [DisplayName("Pris")]
        [Required(ErrorMessage = "Pris är obligatoriskt")]
        [Range(0, 1000,
        ErrorMessage = "Pris måste vara mellan 0-1000")]
        public int Price { get; set; }

        [DisplayName("Type")]
        [Required(ErrorMessage = "Typ är obligatoriskt")]
        public int DishTypeId { get; set; }

        public virtual DishType? DishType { get; set; } = null!;
        public virtual ICollection<OrderDish> OrderDishes { get; set; }

        [JsonIgnore]
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}

PizzaREAL/Models/DishType.cs
using System;
using System.Collections.Generic;

namespace PizzaREAL.Models
{
    public partial class DishType
    {
        public DishType()
        {
            Dishes = new HashSet<Dish>();
        }

        public int DishTypeId { get; set; }
        public string Description { get; set; } = null!;

        public virtual ICollection<Dish> Dishes { get; set; }
    }
}

PizzaREAL/ViewModels/AddDishViewModel.cs
using PizzaREAL.Models;

namespace PizzaREAL.ViewModels
{
    public class AddDishViewModel
    {
        public Dish NewDish { get; set; }
        public List<Ingredient>? Ingredients { get; set; }
        public List<DishType>? DishTypes { get; set; }
        public int[] IngredientIds { get; set; }

    }
}

PizzaREAL/Controllers/DishController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PizzaREAL.Services;
using PizzaREAL.ViewModels;

namespace PizzaREAL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DishController : Controller
    {
        private readonly IDishService _dishService;
        private readonly IIngredientService _ingredientService;

        public DishController(IDishService dishService, IIngredientService ingredientService)
        {
            _dishService = dishService;
            _ingredientService = ingredientService;
        }

        public IActionResult GetDishes()
        {
            return View(_dishService.GetDishes());
        }

        public IActionResult AddDish()
        {

            return View(AddDishViewModel());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult AddDish(AddDishViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.NewDish.Ingredients = _ingredientService.GetRange(model.IngredientIds);
                _dishService.AddDish(model.NewDish);
                ViewBag.Dish = "Maträtten las till i databasen";
                ModelState.Clear();
            }

            return View(AddDishViewModel());
        }

        public IActionResult UpdateDish(int id)
        {
            var viewModel = AddDishViewModel();
            viewModel.NewDish = _dishService.GetById(id);
            
            return View(viewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult UpdateDish(AddDishViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.NewDish.Ingredients = _ingredientService.GetRange(viewModel.IngredientIds);
                _dishService.UpdateDish(viewModel.NewDish);

                ViewBag.Dish = "Maträtten uppdaterades!";
                ModelState.Clear();
                return View("GetDishes", _dishService.GetDishes());
            }
            else
            {
                return View(viewModel);
            }
        }




        private AddDishViewModel AddDishViewModel()
        {
            AddDishViewModel addDishViewModel = new AddDishViewModel();
            addDishViewModel.Ingredients = _ingredientService.GetIngredients();
            addDishViewModel.DishTypes = _dishService.GetDishTypes();

            return addDishViewModel;
        }
    }
}

PizzaREAL/Views/Dish/AddDish.cshtml
@model PizzaREAL.ViewModels.AddDishViewModel

@if (ViewBag.Dish != null)
{
    <div class="alert alert-dismissible green">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        @ViewBag.Dish
    </div>
}

<div class="container-sm">
    <form asp-controller="Dish" asp-action="AddDish" method="Post">
        <fieldset>
            <legend>Lägg till maträtt</legend>

            <div class="row">
                <div class="col-sm">
                    <label asp-for="NewDish.DishName" class="form-label mt-4"></label>
                    <input type="text" class="form-control" asp-for="NewDish.DishName" maxlength="100" />
                    <span asp-validation-for="NewDish.DishName" class="text-danger"></span>
                </div>
                <div class="col-sm">
                    <label asp-for="NewDish.Price" class="form-label mt-4"></label>
                    <input type="number" class="form-control" asp-for="NewDish.Price" maxlength="100" />
                    <span asp-validation-for="NewDish.Price" class="text-danger"></span>
                </div>
                <div class="col-sm">
                    <label asp-for="NewDish.DishType" class="form-label mt-4">Typ av maträtt</label>
                    <select class="form-control" asp-for="NewDish.DishTypeId">

                        @foreach (var dishType in Model.DishTypes)
                        {
                            <option value="@dishType.DishTypeId">@dishType.Description</option>
                        }
                    </select>
                    <span asp-validation-for="NewDish.DishName" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <label asp-for="NewDish.Description" class="form-label mt-4"></label>
                    <textarea style="resize:none" class="form-control" asp-for="NewDish.Description" rows="9"></textarea>
                    <span asp-validation-for="NewDish.Description" class="text-danger"></span>
                </div>
                <div class="col-sm">
                    <label class="form-label mt-4">Ingredienser</label>
                    <select size="10" multiple class="form-control" asp-for="IngredientIds" >

                        @foreach (var ingredient in Model.Ingredients)
                        {
                            <option value="@ingredient.IngredientId">@ingredient.IngredientName</option>

                        }
                    </select>
                    <span asp-validation-for="NewDish.Description" class="text-danger"></span>

                </div>
            </div>
            <div class="form-group">
                <br />
                <a asp-controller="Dish" asp-action="GetDishes" class="btn grey">Tillbaka</a>
                <button type="submit" class="btn green">Spara maträtt</button>
            </div>



        </fieldset>
    </form>
</div>

PizzaREAL/Views/Dish/GetDishes.cshtml
@model List<PizzaREAL.Models.Dish>

@if (ViewBag.Dish != null)
{
    <div class="alert alert-dismissible green">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        @ViewBag.Dish
    </div>
}

<table class="table">
    <tr>
        <th>
            <h3>Maträtter</h3>
        </th>
        <th class="float-right extend">
            <a asp-controller="Dish" asp-action="AddDish" class="float-left btn green">
                Lägg till maträtt
            </a>
        </th>
    </tr>
</table>

<h3>Pizzor</h3>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Namn</th>
            <th scope="col">Beskrivning</th>
            <th scope="col">Ingredienser</th>
            <th scope="col">Pris</th>
            <th scope="col">Ändra</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var dish in Model.Where(d => d.DishTypeId == 1))
        {
            <tr>
                <th scope="row">@dish.DishName</th>
                <td>@dish.Description</td>
                <td>
                    @foreach (var ingridient in dish.Ingredients)
                    {
                        @ingridient.IngredientName @Html.Raw(", ")
                    }
                </td>
                <td>@dish.Price</td>
                <td>
                    <a asp-controller="Dish" asp-action="UpdateDish" method="get" class="btn grey" asp-route-id=@dish.DishId>
                        <i class="bi bi-pencil"></i> Ändra
                    </a>
                </td>
            </tr>
        }

</table>

<h3>Pasta</h3>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Namn</th>
            <th scope="col">Beskrivning</th>
            <th scope="col">Ingredienser</th>
            <th scope="col">Pris</th>
            <th scope="col">Ändra</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var dish in Model.Where(d => d.DishTypeId == 2))
        {
            <tr>
                <th scope="row">@dish.DishName</th>
                <td>@dish.Description</td>
                <td>
                    @foreach (var ingridient in dish.Ingredients)
                    {
                        @ingridient.IngredientName @Html.Raw(", ")
                    }
                </td>
                <td>@dish.Price</td>
                <td>
                    <a asp-controller="Dish" asp-action="UpdateDish" method="get" class="btn grey" asp-route-id=@dish.DishId>
                        <i class="bi bi-pencil"></i> Ändra
                    </a>
                </td>

            </tr>
        }
</table>

<h3>Sallader</h3>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Namn</th>
            <th scope="col">Beskrivning</th>
            <th scope="col">Ingredienser</th>
            <th scope="col">Pris</th>
            <th scope="col">Ändra</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var dish in Model.Where(d => d.DishTypeId == 3))
        {
            <tr>
                <th scope="row">@dish.DishName</th>
                <td>@dish.Description</td>
                <td>
                    @foreach (var ingridient in dish.Ingredients)
                    {
                        @ingridient.IngredientName @Html.Raw(", ")
                    }
                </td>
                <td>@dish.Price</td>
                <td>
                    <a asp-controller="Dish" asp-action="UpdateDish" method="get" class="btn grey" asp-route-id=@dish.DishId>
                        <i class="bi bi-pencil"></i> Ändra
                    </a>
                </td>

            </tr>
        }
</table>

PizzaREAL/Views/Dish/UpdateDish.cshtml
@model PizzaREAL.ViewModels.AddDishViewModel

@if (ViewBag.Dish != null)
{
    <div class="alert alert-dismissible green">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        @ViewBag.Dish
    </div>
}
<div class="container-sm">
    <form asp-controller="Dish" asp-action="UpdateDish" method="Post">
        @Html.HiddenFor(model => model.NewDish.DishId)
        <fieldset>
            <legend>Ändra maträtt</legend>

            <div class="row">
                <div class="col-sm">
                    <label asp-for="NewDish.DishName" class="form-label mt-4"></label>
                    <input type="text" class="form-control" asp-for="NewDish.DishName" maxlength="100" />
                    <span asp-validation-for="NewDish.DishName" class="text-danger"></span>
                </div>
                <div class="col-sm">
                    <label asp-for="NewDish.Price" class="form-label mt-4"></label>
                    <input type="number" class="form-control" asp-for="NewDish.Price" maxlength="100" />
                    <span asp-validation-for="NewDish.Price" class="text-danger"></span>
                </div>
                <div class="col-sm">
                    <label asp-for="NewDish.DishType" class="form-label mt-4">Typ av maträtt</label>
                    <select class="form-control" asp-for="NewDish.DishTypeId">

                        @foreach (var dishType in Model.DishTypes)
                        {
                            <option value="@dishType.DishTypeId">@dishType.Description</option>
                        }
                    </select>
                    <span asp-validation-for="NewDish.DishName" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <label asp-for="NewDish.Description" class="form-label mt-4"></label>
                    <textarea style="resize:none" class="form-control" asp-for="NewDish.Description" rows="9"></textarea>
                    <span asp-validation-for="NewDish.Description" class="text-danger"></span>
                </div>
                <div class="col-sm">
                    <label class="form-label mt-4">Ingredienser</label>
                    <select size="10" multiple class="form-control" asp-for="IngredientIds" >

                        @foreach (var ingredient in Model.Ingredients)
                        {
                            <option value="@ingredient.IngredientId">@ingredient.IngredientName</option>

                        }
                    </select>
                    <span asp-validation-for="NewDish.Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <br />
                <a asp-controller="Dish" asp-action="GetDishes" class="btn grey">Tillbaka</a>
                <button type="submit" class="btn green">Uppdatera maträtt</button>
            </div>
        </fieldset>
    </form>
</div>