PizzaREAL/Models/Ingredient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PizzaREAL.Models
{
    public partial class Ingredient
    {
        public Ingredient()
        {
            Dishes = new HashSet<Dish>();
        }

        [NotMapped]
        public int IngredientId { get; set; }
        [DisplayName("Namn")]
        [StringLength(20, ErrorMessage = "Namn på ingrediens kan inte vara mer än 20 tecken")]
        public string IngredientName { get; set; } = null!;

        public virtual ICollection<Dish> Dishes { get; set; }
    }
}

PizzaREAL/ViewModels/IngredientViewModel.cs
using PizzaREAL.Models;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PizzaREAL.ViewModels
{
    public class IngredientViewModel
    {
        public Ingredient ActiveIngredient { get; set; }
        public List<Ingredient> Ingredients { get; set; }
    }
}

PizzaREAL/Controllers/IngredientController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PizzaREAL.Models;
using PizzaREAL.Services;
using PizzaREAL.ViewModels;

namespace PizzaREAL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class IngredientController : Controller
    {
        private readonly IIngredientService _ingredientService;

        public IngredientController(IIngredientService ingredientService)
        {
            _ingredientService = ingredientService;
        }

        public IActionResult GetIngredients()
        {
            return View( _ingredientService.GetIngredients());
        }
        public IActionResult AddIngredient()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddIngredient(Ingredient model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Ingredient = "Ingrediensen las till i databasen!";
                ModelState.Clear();
                _ingredientService.AddIngredient(model);
            }
            
            return View();
        }
              
        [HttpGet]
        public IActionResult RemoveIngredient(int id)
        {
            _ingredientService.RemoveIngredient(id);
            ViewBag.Ingredient = "Ingrediens bortagen";
            return View("GetIngredients", _ingredientService.GetIngredients());
        }


        [HttpGet]
        public IActionResult UpdateIngredient(int id)
        {            
            return View(_ingredientService.GetById(id));
        }

        [HttpPost]
        public IActionResult UpdateIngredient(Ingredient model)
        {
            _ingredientService.UpdateIngredient(model);
            ViewBag.Ingredient = "Ingrediensens namn uppdaterad!";
            return View("GetIngredients", _ingredientService.GetIngredients());
        }
    }
}

PizzaREAL/Views/Ingredient/AddIngredient.cshtml
@model PizzaREAL.Models.Ingredient

@if (ViewBag.Ingredient != null)
{
    <div class="alert alert-dismissible green">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        @ViewBag.Ingredient
    </div>
}
<form asp-controller="Ingredient" asp-action="AddIngredient" method="post">


    <fieldset>
        <legend>Lägg till ingrediens</legend>

        <div class="form-group">
            <label asp-for="IngredientName" class="form-label mt-4"></label>
            <input type="text" class="form-control" asp-for="IngredientName" maxlength="50" />
            <span asp-validation-for="IngredientName" class="text-danger"></span>
        </div>


        <br />
        <a asp-controller="Ingredient" asp-action="GetIngredients" class="btn grey">Tillbaka</a>
        <button type="submit" class="btn green">Spara ingrediens</button>

    </fieldset>
</form>

PizzaREAL/Views/Ingredient/GetIngredients.cshtml
@model List<PizzaREAL.Models.Ingredient>

@if (ViewBag.Ingredient != null)
{
    <div class="alert alert-dismissible green">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        @ViewBag.Ingredient
    </div>
}

<table class="table">
    <tr>
        <th>
            <h3>Ingredienser </h3>
        </th>
        <th class="float-right extend">
            <a asp-controller="Ingredient" asp-action="AddIngredient" class="float-left btn green">
                Lägg till ingrediens
            </a>
        </th>
    </tr>
</table>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Namn</th>
            <th scope="col">Ändra</th>
            <th scope="col">Ta bort</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ingredient in Model)
        {
            <tr>
                <th scope="row">@ingredient.IngredientName</th>

                <td>
                    <a asp-controller="Ingredient" asp-action="UpdateIngredient" method="get" class="btn grey" asp-route-id=@ingredient.IngredientId>
                        <i class="bi bi-pencil"></i> Ändra namn
                    </a>


                </td>
                <td>
                    @if (ingredient.Dishes.Count == 0)
                    {

                        <a asp-controller="Ingredient" asp-action="RemoveIngredient" method="get" class="btn red" asp-route-id=@ingredient.IngredientId>
                            <i class="bi bi-trash"></i> Ta bort
                        </a>
                    }
                    else
                    {
                        <p>Ingrediensen finns i minst en maträtt</p>
                    }

                </td>

            </tr>
        }

</table>

PizzaREAL/Views/Ingredient/UpdateIngredient.cshtml
@model PizzaREAL.Models.Ingredient


@if (ViewBag.Ingredient != null)
{
    <div class="alert alert-dismissible green">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        @ViewBag.Ingredient
    </div>
}
<form asp-controller="Ingredient" asp-action="UpdateIngredient" method="post">


    <fieldset>
        <legend>Ändra ingrediensens namn</legend>

        <div class="form-group">
            <label asp-for="IngredientName" class="form-label mt-4"></label>
            <input type="text" class="form-control" asp-for="IngredientName" maxlength="50" />
            <span asp-validation-for="IngredientName" class="text-danger"></span>
        </div>

        @Html.HiddenFor(model => model.IngredientId)



        <br />
        <a asp-controller="Ingredient" asp-action="GetIngredients" class="btn grey">Tillbaka</a>
        <button type="submit" class="btn green">Ändra ingrediensens namn</button>

    </fieldset>
</form>